# Configurações do H2 Database
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Console do H2 (opcional, apenas para acessar a console web do H2)
h2:
  console:
    enabled: true
    path: /h2-console

server:
  port: 8081
