spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Console do H2 (opcional, apenas para acessar a console web do H2)
h2:
  console:
    enabled: true
    path: /h2-console

server:
  port: 8081
